<a href="https://colab.research.google.com/github/Fabricioti/analise_de_dados/blob/master/TrabalhoComplementarAnalisedados2020_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## COVID-19 • Trabalho Complementar Análise de Dados 2020/1


---

**Nome**: Fabrício Silva Faria <br>
**RA**: 31610363

**Descrição**: Utilizando Relatórios de tendências de movimentação
durante a pandemia de COVID‑19. Os relatórios foram importados e refletem solicitações de direções no Mapas da Apple durante o período de 13/01/2020 até 13/06/2020.

**Objetivo**: O objetivo aqui é fazer uma análise na base de dados fornecisa pela Apple sobre as solicitações de direção pelo seu aplicativo de locomoção e conseguir obter informações para análisar os dados e comportamentos dos diferentes países cadastrados e elaborar algumnas questões para serem respondidas e nos auxiliar nesse trabalho de análise exploratório utilizando Numpy e o conhecimento adquirido nas aulas ao longo do semestre.




##01 Exercícios iniciais para aquecimento e configuração da pesquisa sobre o covid19
A seguir irei passar alguns exercícios básicos para que o ambiente esteja preparado e seja possível realizar as consultas mais apuradas logo em seguida.

1. Faça importação do pacote numpy com o nome np.

In [ ]:
import numpy as np

### 2. Faça o upload do conjunto de dados da Apple para uma variável chamada dadoscovid19.


*   Especifique a codificação UTF-8;
*   Adcione o delimitador = ','  ;
*   Utilize a função genfromtxt;



In [ ]:
dadoscovid19 = np.genfromtxt('apple2020.csv',skip_header=True, delimiter = ',',encoding='UTF-8')

print (dadoscovid19)

[[   nan    nan    nan ... 111.52 117.39 128.99]
 [   nan    nan    nan ... 134.41 142.26 142.22]
 [   nan    nan    nan ...  68.45  84.94  88.93]
 ...
 [   nan    nan    nan ... 159.74 189.88 196.89]
 [   nan    nan    nan ... 127.58 166.58 161.09]
 [   nan    nan    nan ... 149.18 180.86 191.24]]


### 3. Informe o número de linhas lidas do arquivo:

In [ ]:
print(len(dadoscovid19)) 

4691


### 4. Informe o número de dimensões a variável dadoscovid19 possui:

In [ ]:
print(dadoscovid19.ndim)  


2


### 5. O que a função shape esta retornando ?

In [ ]:
print(dadoscovid19.shape)  


(4691, 285)


### 6. Exiba o dado que está na 5ª linha da 8ª coluna:

In [ ]:
print(dadoscovid19[4, 7])

102.98


### 7. Exiba as 10 primeiras linhas do conjunto de dados:

In [ ]:
print(dadoscovid19[10:])

[[   nan    nan    nan ... 109.52 109.81  98.61]
 [   nan    nan    nan ... 119.63 118.91 139.35]
 [   nan    nan    nan ... 109.27 126.28 132.94]
 ...
 [   nan    nan    nan ... 159.74 189.88 196.89]
 [   nan    nan    nan ... 127.58 166.58 161.09]
 [   nan    nan    nan ... 149.18 180.86 191.24]]


##02 Pesquisa sobre o covid19 - Relatórios de tendências de movimentação Apple

A seguir encoontra-se os exercícios mais apurados para realização de uma análise dos dados dos relátorios de tendências de movimentação disponível no [site da Apple](https://www.apple.com/covid19/mobility) e já importado e configurado no exercício anterior.

### 1. Selecione todas as linhas da coluna regiões dentro da base de dados

In [ ]:
print(dadoscovid19[:,1])

[nan nan nan ... nan nan nan]


### 2. Crie um vetor numpy chamado data14 que irá pegar todas as linhas da coluna 14/01/2020 representando todos os dados daquele dia

In [ ]:
data14 = np.array(dadoscovid19[:,7], dtype=int)
print (data14)

[ 95 100  97 ... 102 101  95]


### 3. Qual é o valor médio encontrado na data 14/01/2020?

In [ ]:
np.median(data14)


101.0

### 4. Qual foi o maior valor encontrado no dia 14/01/2020

In [ ]:
 print(data14.max())

169


### 5. Qual foi o menor valor encontrado no dia 14/01/2020

In [ ]:
print(data14.min())

-9223372036854775808


### 6. Crie um vetor para pegar todos os dados do dia 14/02/2020

In [ ]:
data1402 = np.array(dadoscovid19[:,35], dtype=int)
print (data1402)

[ 94  90  96 ... 100 106 114]


### 7. Crie um vetor para pegar todos os dados do dia 14/03/2020

In [ ]:
data1403 = np.array(dadoscovid19[:,67], dtype=int)
print (data1403)

[ 24  37  84 ... 110 100 130]


### 8. Compare a média do dia 14/01, 14/02 e 14/03 e veja se aumentou ou diminuiu

In [ ]:

print('\n DIA 14/01:',np.median(data14),  '\n DIA 14/02:',np.median(data1402),  '\n DIA 14/03:',np.median(data1403))
 


 DIA 14/01: 101.0 
 DIA 14/02: 105.0 
 DIA 14/03: 109.0


### 9. Crie um vetor brasil_transito para pegar todos os dados de solicitação de transito do Brasil

In [ ]:
brasil_transito = np.array(dadoscovid19[12,6:], dtype=int)
print (brasil_transito)

[                 100                   99                  100
                  101                  113                  114
                   91                   97                   98
                   97                   98                  109
                  111                   88                   92
                   95                   94                   96
                  109                  109                   83
                   92                   92                   93
                   96                  114                  117
                   86                   99                   95
                   98                   98                  115
                  123                   92                   95
                   99                  102                  109
                  141                  140                  103
                  102                   99                   92
                   91                  1

### 10. Informe o valor máximo que houve de solicitações do Brasil em um único dia

In [ ]:
print(brasil_transito.max())

141


### 11. Informe o valor mínimo que houve de solicitações do Brasil em um único dia

In [ ]:
print(brasil_transito.min())

-9223372036854775808


### 12. Informe no dia 20/01/2020 qual o valor retornou para solicitações de direção no Brasil

In [ ]:
print(dadoscovid19[12, 13])


97.54


### 13. Informe no dia 25/03/2020 qual foi o valor retornado para solicitações de caminhada na Argentina

In [ ]:
print(dadoscovid19[3, 78])

10.92


### 14. Compare os dados do dia 25/03(questão anterior) com os dados do mesmo dia do Brasil para buscas de caminhada.

In [ ]:
print('Argentina:', dadoscovid19[3, 78], '\n Brasil:', dadoscovid19[14, 78] )

Argentina: 10.92 
 Brasil: 27.96


### 15. Compare os dados de direção, caminhada e trânsito no Canadá no dia 30/01/2020 

In [ ]:
print('CANADA(30/01/20):','\n Direção:',dadoscovid19[19, 23],' \n Caminhada:', dadoscovid19[20, 23], '\n Trânsito:', dadoscovid19[21, 23])

CANADA(30/01/20): 
 Direção: 109.0  
 Caminhada: 97.63 
 Trânsito: 115.16


### 16. Informe qual foi a pontuação para solicitações de caminhada no Chile no dia 25/03

In [ ]:
print(dadoscovid19[23, 78])

22.76


### 17. Informe a pontuação para Trânsito na França no dia 01/04/2020

In [ ]:
print(dadoscovid19[43, 85])

11.92
